name: Build and Push Custom Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'
        type: string
      push_to_registry:
        description: 'Push to Docker registry'
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Stop docker
        run: sudo systemctl stop docker
      
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          build-mount-path: '/var/lib/docker'
      
      - name: Start docker
        run: sudo systemctl start docker
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        if: ${{ inputs.push_to_registry }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate version file
        run: |
          COMMIT_HASH=$(git log -1 --pretty=format:"%h"|tail -1)
          VERSION="0.17.0"
          echo "VERSION = \"${VERSION}-${COMMIT_HASH}\"" > frigate/version.py
      
      # Removido passo de converter nome do repositório para lowercase, pois não é mais usado
      
      - name: Build and push to GitHub Container Registry
        if: ${{ inputs.push_to_registry }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/main/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          target: frigate
          tags: |
            ghcr.io/cbmedeiros/frigate:${{ inputs.tag }}
            ghcr.io/cbmedeiros/frigate:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build only (no push)
        if: ${{ !inputs.push_to_registry }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/main/Dockerfile
          push: false
          platforms: linux/amd64
          target: frigate
          tags: frigate:${{ inputs.tag }}
